### ISSUE TITLE
Decouple the EdgeLoader from VertexClassifier rules in a generic way

### ISSUE THREAD

**Issue by saucam** [astrolabsoftware/grafink#12]
Currently, the ```MakeEdge``` Dataset contains a column ```propVal``` which is specific to SimilarityClassifier. We should add a more generic column like List[Any] that will contain the key and values for a particular edge to be added.

**Comment by saucam** [comment]
Will revert to using DataFrame instead of Dataset, since cannot have generic types (lack of variance and Encoders https://issues.apache.org/jira/browse/SPARK-22351) for datasets

**Comment by JulienPeloton** [comment]
Good catch. Would that change imply any performance degradation?

**Comment by saucam** [comment]
Just tested, no degradation

**Comment by JulienPeloton** [comment]
Excellent, thanks!
