### ISSUE TITLE
[Data ingestion] Add new vertex properties

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/grafink#26]
Based on #25, I list here the properties that should be added to vertices to better disentangle between alerts:
 
- [x] add the column `candid`
- [x] add the column `candidate.jd`
- [x] add the column `candidate.magpsf`
- [x] add the column `candidate.sigmapsf`

**Comment by saucam** [comment]
The new properties added are
```
"candid",
"jd",
 "magpsf",
 "sigmapsf"
```
