### ISSUE TITLE
[Data ingestion/Minor] Add a new vertex property: rowkey

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/grafink#27]
In order to enable correspondence between different HBase tables from Fink and tables from grafink, we need to add a new vertex property:

- [x] define a new vertex property in the schema which is the `rowkey` of the other HBase table used by Fink. This `rowkey` is a string simply made of `objectId_jd`  (jd = `candidate.jd`).
- [x] add `rowkey` for each vertex
- [x] This new vertex property will be then used to create indices for example
- [x] There is also a minor change to homogeneize the two tables: renaming vertex name in grafink (which is `vertex` for the moment) as `alert`.

**Comment by saucam** [comment]
I see from data that ```candidate.jd``` is a double field with values like 

```
+---------------+
|jd             |
+---------------+
|2458789.0256944|
|2458789.0426273|
|2458789.0316204|
|2458789.0311458|
|2458789.0270486|
+---------------+
```

Do we really want these as part of ```rowkey``` ?

**Comment by JulienPeloton** [comment]
Yes, but would you suggest something different?

Truncating `jd` would not be good, because the conversion `Julian Date` to `UTC` for example depends on all digits. Hence we put all `jd` inside the `rowkey` (string format).

**Comment by saucam** [comment]
Ok added as mentioned in the ticket
