### ISSUE TITLE
Parquet database updates

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/grafink#32]
### Data change

The original Parquet data base has been recently updated with modifications from Fink:
- fink-science (0.3.6): https://github.com/astrolabsoftware/fink-science/pull/65
- fink-broker (0.7.0): https://github.com/astrolabsoftware/fink-broker/pull/396

### Column name addition/modification

The main modifications for grafink are the following:
- previous `snnscore` has its name changed into `snn_snia_vs_nonia`
- new column name `snn_sn_vs_all`
- new column name `nalerthist`

In addition, the asteroid data (`roid`) keeps its name, but the data has been improved (should lead to less spurious connections).

### Similarity computation

The similarity computation does not change for the moment.

### Data path

Old data can be found at 

```
/user/julien.peloton/ztf_alerts/science_reprocessed_old
```

new data is at the usual path

```
/user/julien.peloton/ztf_alerts/science_reprocessed
```

**Comment by saucam** [comment]
Thanks @JulienPeloton , I have made the necessary changes to the config

**Comment by JulienPeloton** [comment]
Done in #36 #31
