### ISSUE TITLE
[Data ingestion] Update vertex properties + new supernova recipe

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/grafink#35]
Based on PR #34, here are the change to perform to improve the data:

### Addition of new alert vertex properties

We should add these new properties (I quote their name from the Parquet dataset):

- `candidate.ndethist` (int)
- `candidate.ra` (float)
- `candidate.dec` (float)
- `candidate.drb` (float)
- `candidate.ssdistnr` (float)
- `candidate.ssnamenr` (string or null)
- `candidate.fid` (int)
- `candidate.neargaia` (float or null)
- `candidate.distpsnr1` (float or null)
- `snn_sn_vs_all` (float)
- `mulens.ml_score_1` (float)
- `mulens.ml_score_2` (float)

And we should finish to add all `catalog` subcategories.

### Modification of the supernova recipe

The current `supernova` recipe is leading to zero links. I propose to change to:

```
snn_snia_vs_nonia > 0.75
AND
snn_sn_vs_all > 0.75
AND
drb > 0.5
AND
cdsxmatch in either 
	["galaxy", "Galaxy", "EmG", "Seyfert", "Seyfert_1", "Seyfert_2", 
	"BlueCompG", "StarburstG", "LSB_G", "HII_G", "High_z_G", "GinPair", 
	"GinGroup", "BClG", "GinCl", "PartofG", "Unknown", 
	"Candidate_SN*", "SN", 	"Transient"]
AND
ndethist < 400
AND
classtar > 0.4
```

This should give about 2,444 `alert` vertices connected to the similarity vertex `supernova` for the same period of time than the study in PR #34.

**Comment by saucam** [comment]
@JulienPeloton  apart from the above changes, do we need to drop any existing vertex property?

**Comment by JulienPeloton** [comment]
No, we do not need to drop existing vertex properties. Thanks!

**Comment by saucam** [comment]
```snn_sn_vs_all``` is Double in the reprocessed data

**Comment by JulienPeloton** [comment]
Done in #38
